user_user:
    resource: "@UserUserBundle/Resources/config/routing.xml"
    prefix:   /user

home_home:
    resource: "@HomeHomeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@FOSUserBundle/Controller/"
    type:     annotation

home:
    resource: "@AppBundle/Controller/"
    type: annotation
 
